Repository programacion-6/Opcion1FakeOrgasm, pull requests merged in 2024-08, with the labels that each got.

#13 Test/ticket-17/unit-testing-books-management
  Tests/.gitignore
  Tests/BooksManagement/BookRepositoryTests.cs
  Tests/BooksManagement/BookTests.cs
  Tests/Tests.csproj
  Tests/UnitTest1.cs
Labels: test

#18 Hotfix/no ref/fine loan bad formatting
  LibrarySystem/Program.cs
  LibrarySystem/src/View/FormatterFactories/Concrete/FineFormatterFactory.cs
  LibrarySystem/src/View/RenderingFormatters/DebtFormatters/VerboseFineFormatter.cs
  LibrarySystem/src/View/RenderingFormatters/LoanFormatters/SimpleLoanFormatter.cs
  LibrarySystem/src/View/RenderingFormatters/LoanFormatters/VerboseLoanFormatter.cs
Labels: bug

#19 Develop
  LibrarySystem/Program.cs
  LibrarySystem/src/View/FormatterFactories/Concrete/FineFormatterFactory.cs
  LibrarySystem/src/View/RenderingFormatters/DebtFormatters/VerboseFineFormatter.cs
  LibrarySystem/src/View/RenderingFormatters/LoanFormatters/SimpleLoanFormatter.cs
  LibrarySystem/src/View/RenderingFormatters/LoanFormatters/VerboseLoanFormatter.cs
Labels: release

#10 Refactor of Patron and Book controllers
  LibrarySystem/.gitignore
  LibrarySystem/LibrarySystem.csproj
  LibrarySystem/Program.cs
  LibrarySystem/src/Controller/BookManagement/BookControllerAsText.cs
  LibrarySystem/src/Controller/BookManagement/BookRepositoryHandler.cs
  LibrarySystem/src/Controller/BookManagement/BookSearcher.cs
  LibrarySystem/src/Controller/Concrete/BookControllerAsText.cs
  LibrarySystem/src/Controller/Concrete/PatronControllerAsText.cs
  LibrarySystem/src/Controller/PatronManagement/PatronControllerAsText.cs
  LibrarySystem/src/Controller/PatronManagement/PatronInterfaceHandler.cs
  LibrarySystem/src/Controller/PatronManagement/PatronSearcher.cs
Labels: refactor
